ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MT,MDL_MB,MDL_MS,MDL_MH,MDL_MALP,MDL_MTA
     $ ,MDL_MD,MDL_MZ,MDL_MMU,MDL_MU,MDL_MC,MDL_MW,MDL_ME

      COMMON/MASSES/ MDL_MT,MDL_MB,MDL_MS,MDL_MH,MDL_MALP,MDL_MTA
     $ ,MDL_MD,MDL_MZ,MDL_MMU,MDL_MU,MDL_MC,MDL_MW,MDL_ME


      DOUBLE PRECISION MDL_WW,MDL_WZ,MDL_WT,MDL_WH,MDL_WALP

      COMMON/WIDTHS/ MDL_WW,MDL_WZ,MDL_WT,MDL_WH,MDL_WALP


      DOUBLE COMPLEX GC_56, GC_91, GC_92, GC_102, GC_110

      COMMON/COUPLINGS/ GC_56, GC_91, GC_92, GC_102, GC_110

