ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of ALP'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_56 = ', GC_56
      WRITE(*,2) 'GC_91 = ', GC_91
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_102 = ', GC_102
      WRITE(*,2) 'GC_110 = ', GC_110
